Update for MacHyperVSupport v0.9.8 (#40)
```
* Update License

Updates license following https://github.com/acidanthera/MacHyperVSupport/commit/1e854f8e19fe41134d0f0348a11a4028eca771a6

* Remove WS2022 SSDT, Update ACPI patches

* Add MacHyperVFramebuffer, update configuration

* Update OpenCore, MacHyperVSupport versions

* Remove VMHide kext

Replaces with more direct `hv_vmm_present` patch. For whatever reason, this kext does not reliably load w/ Lilu.

We replace this with a kernel patch as a suggested workaround from https://github.com/Qonfused/OSX-Hyper-V/issues/46#issuecomment-2813907377.

* Fix IOGraphicsFamily paths

Fixes IOGraphicsFamily paths and removes MaxKernel version.

* Remove ACPI0007 objects from SSDT-HV-DEV

Syncs changes following https://github.com/acidanthera/OpenCorePkg/commit/f4e7e29335f6b2c9d087de37a1d9031de8ca2d91.

* Disable MacHyperVFramebuffer injection

This keeps MacHyperVFramebuffer in the EFI/OC/Kexts directory to be found later for post-installation.

* Add post-install script

Automates installing Hyper-V daemons and the MacHyperVFramebuffer kext.

* Update README, post-install script instructions

Resolves #45 and #47.
```

diff --git a/.github/workflows/oce-build.yml b/.github/workflows/oce-build.yml
--- a/.github/workflows/oce-build.yml
+++ b/.github/workflows/oce-build.yml
@@ -65,15 +65,19 @@ jobs:
         name: Validate OCE-Build output
         shell: pwsh
         run: |
-          $OCVALIDATE = 'dist\Utilities\ocvalidate\ocvalidate.exe';
-          $PLIST_PATH = 'dist\EFI\OC\config.plist';
-          Start-Process -Wait $OCVALIDATE -NoNewWindow -ArgumentList $PLIST_PATH;
+          & 'dist\Utilities\ocvalidate\ocvalidate.exe' 'dist\EFI\OC\config.plist' |
+            Tee-Object -FilePath ocvalidate.log
+          if (Select-String -Path ocvalidate.log -Pattern 'Found \d+ issues') {
+            Write-Error "Validation failed, please check output for details."
+            exit 1
+          }
       # Handles compression and lock-hash generation for upload task.
       #
       # This stores a hash of the output build's lockfile to associate with the
       # output EFI directory. This is useful when running concurrent builds with
       # this workflow in a matrix for testing prior or future OpenCore versions.
       - id: prepare-efi
+        if: always()
         name: Prepares EFI directory for upload
         shell: sh
         run: |
@@ -89,7 +93,9 @@ jobs:
       # Uploads EFI with a short-sha slug. The uploaded EFI will be available
       # for download after the current job run as finished.
       - name: Upload built EFI
+        if: always()
         uses: actions/upload-artifact@v4
         with:
           name: EFI-${{ steps.prepare-efi.outputs.LOCKFILE_HASH }}
           path: EFI.zip
+          retention-days: 7
